# Caution: this file may regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision C:/source/boards/Projects/CII_Starter_Kit-v6.0.1/Examples/CII_Starter_demonstrations/CII_Starter_SD_Card_Audio/CII_Starter_SD_Card_Audio.qpf
project_close